---
- hosts: laptops
  roles:
    - { role: common, tags: ['common'] }
    - { role: development, tags: ['dev', 'development'] }
    - { role: gui, tags: ['gui'] }
    - { role: video, tags: ['video'] }
    - { role: audio, tags: ['audio'] }
