---
#- include: widevine.yml
#  tags: ['widevine']
#  become: yes

# TODO: ensure correct packages get installed for correct distro
- name: install video packages
  package:
    name: "{{item}}"
    state: latest
  with_items: "{{video_packages}}"
  become: yes
