---
- include: packages.yml
  tags: ['packages']
  become: yes

- include: vim.yml
  tags: ['vim']

- include: dotfiles.yml
  tags: ['dotfiles']

- include: git.yml
  tags: ['git']

- include: fonts.yml
  tags: ['fonts']
  become: yes
