---
- name: install void linux packages
  package:
    name: "{{item}}"
    state: latest
    #use: xbps
  with_items: "{{void_packages}}"
  when: ansible_distribution == 'void'

# TODO: add arch linux packages
# pip: pip install nvpy
