---
# TODO: figure out how to make sure the right packages get installed for the
# right distro (void for void, arch for arch)
- name: install vim-related packages
  package:
    name: "{{item}}"
    state: latest
  with_items: "{{vim_packages}}"

- name: clone vimrc repo
  git:
    repo: git@github.com:creisor/.vim.git
    dest: "/home/{{laptop_user}}/.vim"
    accept_hostkey: yes

- name: symlink .vimrc
  file:
    src: "/home/{{laptop_user}}/.vim/vimrc"
    dest: "/home/{{laptop_user}}/.vimrc"
    owner: "{{laptop_user}}"
    group: "{{laptop_user}}"
    state: link
