---
# TODO: ensure the right packages get installed for the right distro
- name: install audio packages
  package:
    name: "{{item}}"
    state: latest
  with_items: "{{audio_packages}}"
  become: yes
